// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import { defineConfig } from 'tsup';

export function tsup() {
  return defineConfig(
      {
    "bundle": false,
    "clean": true,
    "dts": true,
    "entry": [
      "src/**/*.ts",
      "!src/scripts/**/*"
    ],
    "format": [
      "cjs",
      "esm"
    ],
    "minify": false,
    "outDir": "lib",
    "shims": true,
    "sourcemap": true,
    "splitting": false,
    "onSuccess": "ts-node src/scripts/make-scripts-executable.ts"
  }
  );
}
