// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import { defineConfig } from 'vitest/config';

export default defineConfig(
    {
    "test": {
      "clearMocks": true,
      "coverage": {
"100": true,
"provider": "v8",
"reporter": [
  "cobertura",
  "text",
  "html",
  "clover",
  "json"
]
      },
      "exclude": [
"node_modules",
"dist",
".idea",
".git",
".cache"
      ],
      "globals": true,
      "outputFile": "junit.xml",
      "reporters": [
"junit"
      ],
      "silent": true,
      "watch": false
    }
  }
);
